'use strict';

var map        = require('map-stream');
var glob       = require('glob');
var path       = require('path');
var changeCase = require('change-case');

// Should refactor into config
var extensions = ['.js', '.jsx'];
var checkExtension = function(ext) {
  return extensions.filter(function(e) { return ext === e; }).length > 0;
}


const indexJSCallback = function(file, cb) {
  const fileSpec   = file.path + '/*.js*';
  let str        = `// this file is generated by the build process ${new Date() + ''}\n\n`;

  file.path  += '/index.js';

  const exportNames = [];
  const files = glob.sync(fileSpec);
  const dash = /-/;

  files.forEach( f => {
    let { name, ext } = path.parse(f);
    if( name === 'index' && checkExtension(ext) ) {
      return;
    }
    const rname = dash.test(name) ? changeCase.pascalCase(name) : name;
    exportNames.push(rname);
    if( !checkExtension(ext) ) {
      name = `${name}${ext}`;
    }
    str += `import ${rname} from './${name}';\n`;
  });

  str += `\n\nmodule.exports = {\n    ${exportNames.join(',\n    ')} \n};\n\n`;
  file.contents = new Buffer(str);

  cb(null, file);
};

module.exports = function() { return map(indexJSCallback); };


